# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.
#   - Full reference at http://www.appveyor.com/docs/appveyor-yml

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Visual Studio 2015

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
  nuget restore src\LigerShark.TemplateBuilder.sln

build_script:
  - ps: .\appveyor.ps1

environment:
  NuGetApiKey:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT

artifacts:
  - path: 'OutputRoot\*.nupkg'
  - path: 'OutputRoot\**\TemplateBuilder*.dll'
  - path: 'OutputRoot\**\TemplateBuilder*.pdb'
  - path: 'OutputRoot\**\TemplateBuilder*.config'

nuget:
  account_feed: true
  project_feed: true
